config/routes.rb
Rails.application.routes.draw do
  resources :books
  delete '/books/:id', to: 'books#destroy', as: :destroy_book
  root to: 'homes#top'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @books = Book.all
    @book = Book.new
  end
  
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book)
  else
   render :index
  end
end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book =Book.find(params[:id])
  end
  
  def update
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = 'Book was successfully updated.'
    redirect_to book_path(@book)
  else
    render :edit
   end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h4>Editing Book</h4>

<div class="error"><% if @book.errors.any? %>
 <%= @book.errors.count %>error prohibited this book from being saved:
 <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>
</div>
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>

<%=link_to "Show",book_path(@book.id) %>|<a href="/books">Back</a>

app/views/books/index.html.erb
<h4>Books</h4>
<table>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </tr>
  <% @books.each do |book| %>
  <tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to "Show", book_path(book.id) %></td>
   <td><%= link_to "Edit", edit_book_path(book.id) %></td>
   <td><%= link_to "Destroy",destroy_book_path(book.id), method: :delete, "data-confirm" =>"Are you sure?" %></td>
  </tr>
 <% end %>
</table>

<h1>New Book</h1>

<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>

<%= form_with model: @book, url: books_path do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with model: @book do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<strong>Title:</strong><p><%= @book.title %></p>

<strong>Body:</strong><p><%= @book.body %></p>

<%= link_to"Edit", edit_book_path(@book.id) %>|<a href="/books">Back</a>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ!</h1>

<p><strong>Bookers</strong>では、様々な書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<a href="/books">start</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <% flash.each do |message_type, message| %>
     <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>